// <auto-generated />
using System;
using InversePropertyAttibute.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InversePropertyAttibute.Migrations
{
    [DbContext(typeof(EFCoreDbContext))]
    partial class EFCoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InversePropertyAttibute.Entities.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OfflineTeacherTeacherId")
                        .HasColumnType("int");

                    b.Property<int?>("OnlineTeacherTeacherId")
                        .HasColumnType("int");

                    b.HasKey("CourseId");

                    b.HasIndex("OfflineTeacherTeacherId");

                    b.HasIndex("OnlineTeacherTeacherId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("InversePropertyAttibute.Entities.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("InversePropertyAttibute.Entities.Course", b =>
                {
                    b.HasOne("InversePropertyAttibute.Entities.Teacher", "OfflineTeacher")
                        .WithMany("OfflineCourses")
                        .HasForeignKey("OfflineTeacherTeacherId");

                    b.HasOne("InversePropertyAttibute.Entities.Teacher", "OnlineTeacher")
                        .WithMany("OnlineCourses")
                        .HasForeignKey("OnlineTeacherTeacherId");

                    b.Navigation("OfflineTeacher");

                    b.Navigation("OnlineTeacher");
                });

            modelBuilder.Entity("InversePropertyAttibute.Entities.Teacher", b =>
                {
                    b.Navigation("OfflineCourses");

                    b.Navigation("OnlineCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
